### ISSUE TITLE
assert instead of ignoring non-temp caches

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/dawn#110]
The line [here](https://github.com/MeteoSwiss-APN/dawn/blob/225dcffc3f8236111619991a5ee6319a9c4e1c70/src/dawn/Optimizer/PassSetCaches.cpp#L106) can be reached with a stencil of the shape
```
stencil foo {
  storage a, b, c;

  Do {
    vertical_region(k_start, k_start) {
      a = b[k + 2];
    }
    vertical_region(k_start + 1, k_end) {
      c = a;
      b = a;
    }
  }
};
```
I don't think this code should be considered illegal and the assert should not be asserting but reolving the problem. Am I missing something?

**Comment by cosunae** [comment]
So for which field does this trigger? a or b?

**Comment by twicki** [comment]
b

**Comment by cosunae** [comment]
ok, I ll debug it. I dont know yet why it triggered. I think the assertion looks correct. 
It does not make too much sense to kcache for an output only field, since there is no data reuse ( it is not read access)
The question is also why b is going inside here
```
  if(field.getIntend() == Field::IK_Output) {
```

but I ll debug

**Comment by twicki** [comment]
this is solved
