### ISSUE TITLE
Static asserts are overly cautious

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/dawn#111]
Currently we merge the field-extents with the stage-extents and add those up for the static asserts. This is too greedy since we're not considering the do-method intervals for the computation of halos in the k-dimension. See example here: We get the assert that we need a halo of 2 despite this is coming form the start_start interval:

```
stencil foo {
  storage a, b, c;
  storage out;

  Do {
    vertical_region(k_start, k_start) {
      a = b;
    }
    vertical_region(k_start + 1, k_end) {
      c = b;
    }
    vertical_region(k_start, k_start) {
      out = c + a[k + 2, j + 1];
    }
  }
};
```

**Comment by twicki** [comment]
Also, if we're already on fixing this part of the code: Should we surpess all the halos that are 0 since the code became extremely verbose with the addition of these static asserts and I think it would be easier readable

**Comment by cosunae** [comment]
@twicki check if this is fixed or not

**Comment by twicki** [comment]
This isssue is resolved
