### ISSUE TITLE
naive code requires BOOST_MPL_INCLUDE

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/dawn#115]
After the update to the new Gritdools version, stencils require `BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS` to be set for unknown reasons. For example, horizontal_diffusion_limiter breaks

**Comment by cosunae** [comment]
We are already generating that define

https://github.com/MeteoSwiss-APN/dawn/blob/master/src/dawn/CodeGen/GridTools/GTCodeGen.cpp#L1082

**Comment by twicki** [comment]
The problem is that Navie Code-gen also requires it. Should we just add these defines also there?

**Comment by cosunae** [comment]
uhmmm why would the naive code gen require that? It does not use mpl, so I dont get it
