### ISSUE TITLE
Table of contents of the docs are not updated

### ISSUE THREAD

**Issue by guoxiaolin** [MeteoSwiss-APN/dawn#186]
Hi,

It's so nice to see this project. Reminds me of so many good memories! Especially with @cosunae 

One small issue I found while trying to browse the docs is that the ToC on this page is not updated https://meteoswiss-apn.github.io/dawn/basics.html. Yet this one is up to date https://meteoswiss-apn.github.io/dawn/. I'm not sure how these pages are generated.

Anyway, the project looks very promising. Wish it a great success!

Xiaolin

**Comment by cosunae** [comment]
thanks a lot @guoxiaolin for reporting it. 
At the moment they are generated by hand, so we will have a look at push them asap.

**Comment by mroethlin** [comment]
this seems to be fixed. At least the tabel of contents in both links is the same.
