### ISSUE TITLE
Refactor dependencies

### ISSUE THREAD

**Issue by havogt** [MeteoSwiss-APN/dawn#238]
![DAA8D4D2-D495-46DA-ABE1-F6BB2BF3F478](https://user-images.githubusercontent.com/5136069/63158020-a6b2e200-c018-11e9-9239-91c37c4aef20.jpeg)

**Comment by twicki** [comment]
This was done in a series of PR's listed here:
https://github.com/MeteoSwiss-APN/dawn/pull/264
https://github.com/MeteoSwiss-APN/dawn/pull/245
https://github.com/MeteoSwiss-APN/dawn/pull/244
https://github.com/MeteoSwiss-APN/dawn/pull/240
