### ISSUE TITLE
StencilDescStatementMapper not correctly working with Ifs

### ISSUE THREAD

**Issue by Stagno** [MeteoSwiss-APN/dawn#261]
If you have a stencil code such as:
```
#include "gridtools/clang_dsl.hpp"
using namespace gridtools::clang;
globals { int global = 0; };

stencil execute {
  storage in_field, out_field;
  void Do() {
    if(global) {
      global++;
      vertical_region(k_start, k_end) {
        // copy fields
        if(global > 0)
          out_field = in_field;
      }
      global--;
      vertical_region(k_start + 1, k_end) {
        if(global > 0)
          out_field = in_field;
      }
      global++;
    }
  }
};
```
the generated run method will be incorrect:
```
 void run() {
    if (m_globals.global) {
      (++m_globals.global);
      m_stencil_81.get_stencil()->run();
      (--m_globals.global);
      (++m_globals.global);
    }
  }
```
The problem is that `StencilDescStatementMapper` visitor in `OptimizerContext.cpp` will fuse the vertical regions together in the same stencil (but on different MultiStages) and substitute only the first encounter of a `VerticalRegionDeclStmt` with a stencil call, regardless of control flow statements that may be in between.

**Comment by twicki** [comment]
globals also are broken if they are accessed outside verical regions. See:
#include "gridtools/clang_dsl.hpp"

using namespace gridtools::clang;

globals { double test = 1; };

stencil foo {
  storage a, b;
  storage out;

  Do {
    vertical_region(k_start, k_end) {
      // global use
      a = b + test;
    }
    test = 2;
    vertical_region(k_start, k_end) {
      // new global use
      c = b + test;
    }
  }
};

**Comment by havogt** [comment]
The second example is tracked in #401.
