### ISSUE TITLE
Unify testing in dawn

### ISSUE THREAD

**Issue by mroethlin** [MeteoSwiss-APN/dawn#262]
Currently, there are three separate tests one needs to run locally in order to reasonably guarantee the same results using jenkins:

* `ctest` in `bundle/build/dawn-prefix/src/dawn-build`
* `make install` in bundle, i.e. the post installation steps if `DAWN_BUNDLE_PYTHON` is on
* the python examples in `/bundle/install/examples/python`

It would be nice to have all those tests running from a single ctest.

**Comment by twicki** [comment]
The reason why it is currently not done as a ctest is that we require the path to the installation of protobuf for the tests to run. A potential solution could be that we generate a script similar to how we do it here https://github.com/MeteoSwiss-APN/gtclang/blob/ff2126836dca04fc3ee8d55ce5362d7a741a7205/test/integration-test/CMakeLists.txt#L145 at install-time and then register that script to ctest. This shouldn't be too hard but is not in the current sprint. We should bring it up in the next planning.

**Comment by havogt** [comment]
I think this is done.

**Comment by cosunae** [comment]
ok, then I ll close
