### ISSUE TITLE
(2) Move away from our own value class to std::variant [2]

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/dawn#293]
Now that we have c++17 support, the Value class in  https://github.com/MeteoSwiss-APN/dawn/blob/e37778538ef09a111f56aaf247cdd7e1cbf2b567/src/dawn/SIR/SIR.h#L280 is depricated

**Comment by jdahm** [comment]
The Value class here serves a broader purpose than std::variant, because it can store a type but be unset, so it still needs some sort of wrapper object to store that information. Wrapping with `std::optional` almost works, but doesn't store the type when unset...

**Comment by jdahm** [comment]
As far as I can tell boost any does not have the ability to store an unset type.
