### ISSUE TITLE
Single empty vertical region compilation results in stack trace

### ISSUE THREAD

**Issue by jmgorius** [MeteoSwiss-APN/dawn#304]
The following code
``` cpp
#include "gridtools/clang_dsl.hpp"

using namespace gridtools::clang;

stencil ssa_issue {
  Do {
    vertical_region(k_start, k_end) {
    }
  }
};
```
cannot be compiled and results in a stack trace with no additional message. See the [attached file](https://github.com/MeteoSwiss-APN/gtclang/files/3646924/stacktrace.txt) for more details.

**Comment by mroethlin** [comment]
can't reproduce this with current dawn / gtclan build
