### ISSUE TITLE
Remove AST -> SIR dependency

### ISSUE THREAD

**Issue by Stagno** [MeteoSwiss-APN/dawn#319]
AST component depends on SIR through `sir::Field` and `sir::VerticalRegion`. AST should be upstream w.r.t. SIR.

- `sir::Field` should be moved to AST
- `sir::VerticalRegion` should be moved into the SIR data container of `ast::VerticalRegionDeclStmt`. Member field `sir::VerticalRegion::Ast` should be moved into `ast::VerticalRegionDeclStmt`.

**Comment by lukasm91** [comment]
This would fix remaining odd dependencies. I think it would be a good idea to take this soon.
