### ISSUE TITLE
Merge behaves differently for Extent and Extents with offsets

### ISSUE THREAD

**Issue by lukasm91** [MeteoSwiss-APN/dawn#369]
`Extent::merge(int offset)` checks 0:  https://github.com/MeteoSwiss-APN/dawn/blob/a8ded67b4a6f8b96e4d45051d31be0b206052896/dawn/src/dawn/IIR/Extents.h#L65

while as

`Extents::merge(Offset)` does not: 
https://github.com/MeteoSwiss-APN/dawn/blob/a8ded67b4a6f8b96e4d45051d31be0b206052896/dawn/src/dawn/IIR/Extents.cpp#L59

Beside the fact I doubt that this is used correctly, this inconsistency looks very dangerous to me and is very likely to cause bugs.

A similar behaviour happens with `add`, but this will be deleted because unused.

**Comment by lukasm91** [comment]
My feeling is that it should be the one ignoring 0 because it doesn't look like the other one is really used (but I am still a bit scared by the difference).

**Comment by Stagno** [comment]
@lukasm91 is it fixed now or with the upcoming PRs?

**Comment by lukasm91** [comment]
Yes. After #376 I am using the same functionality. Good thing was that not all functions were used in the end...
