### ISSUE TITLE
Connect GT4py with dawn for a simple lat-lon example

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/dawn#408]
DoD: connect for a simple example GT4py with dawn via SIR and code generate. Manually compile the TU until we have a clear mode of how to pass compiler flags from dawn upstream or decide who should compile and provide a .so

**Comment by lukasm91** [comment]
We should coordinate with Enrique and Linus how much time they have. It's also not clear to me whether we should put this task into our sprint because this will be done by them I think.

**Comment by cosunae** [comment]
We already coordinated this with Mauro, and we have the green light for this. 
Irrespective of who does it, we need someone from our side to work on this. 
Currently we would have to ways of doing this, from GT4py we can call the python API of the SIR, or from python we serialize protobuf and deserialize it from dawn. 
We need to discuss with GT4py, take a decision, and do a first implementation, even if it is considered a prototype.

**Comment by cosunae** [comment]
Missing: 
 - export the SIR wrapper same way we export dawn compile
 - cleanup the jinja template
 - make protobuf link statically

**Comment by twicki** [comment]
This is the rough roadmap of things. @lukasm91 and @egparedes add things if you see missing ones

- [ ] Create a dawn back end for GT4Py 
- [ ] GT4Py can translate its IR can be into SIR
- [ ] Dawn has python bindings
- [ ] The jinja templates to run code from the python infrastructure are working
- [ ] make dawn pip installable
- [ ] The dawn4py setup is merged into master
- [ ] Clean up on the jinja templates to match the GridTools ones for `bindings.hpp` and `computation.hpp`
- [ ] Clean up the python implementation of the dawn back end
- [ ] Adapt the dawn4py branch to the new CMake infrastructure
- [ ] Add tests into dawn
- [ ] Adapt the templates to match the new header structure
- [ ] Move relevant parts of the python folder to dawn-python and delete the other one

**Comment by lukasm91** [comment]
I created an epic #509  maybe we should clean up this task and create follow-up tasks as tasks and add the roadmap to the epic. @twicki @cosunae @ofuhrer @mbianco

**Comment by twicki** [comment]
so the simple example is done. Try here:

https://github.com/twicki/gt4py2dawn

run `bash scripts/jenkins/run.sh -i` on daint and add the `-l` flag for local runs (ignoring the .env files).
