### ISSUE TITLE
Use modern CMake in Dawn and GTClang

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/dawn#409]

**Comment by jdahm** [comment]
We discussed some sub-tasks to make this large effort more digestible. These are:
1. Merge CMake projects together (#407) (blocks 6)
2. Switch to target-based include directories, compilation flags, etc. (depends on 3, blocks 6)
3. Remove the bundle (blocks 6)
4. Remove yoda from main project (depends on 1)
5. Move `gridtools::clang` to top-level directory in project
6. Create a modern CMake bundle (depends on 3)

**Comment by cosunae** [comment]
thanks @jdahm 
it is not clear how to interpret the combination of 3 & 6. We remove the bundle and create a new bundle?
Could you clarify it? 
I would also like to point out that even if gtclang was merged into dawn, and there is less need now for a bundle we still have the clang-gridtools project with all the dycore examples that still makes use of the bundle. So in case of 3) we would need to find an equivalent solution

**Comment by jdahm** [comment]
Hi @cosunae - The idea behind (3) and (6) was, as you said, ensure there's a bundle-like build option left after the refactor. As a start, that bundle could use yoda, even though yoda is planned to be removed from the dawn/gtclang build process. Later we could incorporate CMake's ExternalProject: https://cmake.org/cmake/help/latest/module/ExternalProject.html
