### ISSUE TITLE
Unstructured vertical solver

### ISSUE THREAD

**Issue by lukasm91** [MeteoSwiss-APN/dawn#413]
We should also have tests for vertical dependencies --> Write a simple vertical solver for unstructured grids on IIR *and* SIR level and check if the generated code is correct.

**Comment by cosunae** [comment]
I didnt understand this one. For vertical solvers there wont be any difference between unstructured or structured isnt ? Can you clarify it?

**Comment by lukasm91** [comment]
There are several things. In most cases, I would also expect to behave them the same way. But at least code generation of vertical offsets is completely different, but also in the optimizers we should make sure that we don't have unexpected interactions between horizontal and vertical extents (like when splitting or merging stages).
