### ISSUE TITLE
Split fieldDimensions into horizontal & vertical

### ISSUE THREAD

**Issue by lukasm91** [MeteoSwiss-APN/dawn#415]
We need to prepare the toolchain to support unstructured masked dimensions. To do that, we should split the "fieldDimensions" (a tuple of booleans) into horizontal and vertical "field dimensions", similarly as we did it for extents and offsets.
- Create a `CartesianFieldDimension` class and a `FieldDimensions` class
- No `UnstructuredFieldDimension` yet
- Define, document and test the proper interface to support all use-cases in the code.

**Comment by Stagno** [comment]
Are you talking about `SIR::fieldDimensions`? I'm asking because I see that it's an array of 3 integers (but maybe they are used as booleans).

**Comment by lukasm91** [comment]
yes they are used as booleans (-1 is false... or the other way round).
