### ISSUE TITLE
Update coding conventions for dawn

### ISSUE THREAD

**Issue by lukasm91** [MeteoSwiss-APN/dawn#418]
Before too many new people start developing in dawn, we should fix our coding conventions.

As a first step, we should document the coding convention properly, at least points where we found that our "default behavior" diverges in a way we don't like. 

There is already some code conventions, but not everything might be up-to-date and partially incomplete.
https://meteoswiss-apn.github.io/dawn/coding.html#style-issues
Maybe we can refer to one of the well-known coding standards and just specify things in more detail where we diverge or have a different approach.

**Comment by lukasm91** [comment]
Ideas:

- Naming of struct vs. class members
- inline in class member functions (no)
- extern in free header functions (no)
- virtual in derived functions (no)
- braces for one-line if-else or loop bodies required (no)
- #pragma once vs include guards
- include order and absolute vs. relative path (same folder -> same library -> other -> std; no absolute path if in same folder)
- east const / west const (east const)

 Parentheses: my personal opinion

**Comment by Stagno** [comment]
contains this: https://github.com/MeteoSwiss-APN/dawn/issues/321
