### ISSUE TITLE
Consistency check for extents and offsets

### ISSUE THREAD

**Issue by lukasm91** [MeteoSwiss-APN/dawn#423]
We need to check whether all extents and offsets are of the grid type that the user promises us.

We already know which grid type we have, so we need to traverse the AST, check all offsets and make sure that they can be casted to that grid type.

This consistency check should be unit tested!

**Comment by lukasm91** [comment]
Not this sprint, maybe next. See blocker.

**Comment by cosunae** [comment]
how do we know which grid type we are using ?

**Comment by cosunae** [comment]
ah ok, see blocker sorry

**Comment by mbianco** [comment]
We need some examples to understand what these checks needs to enforce...

**Comment by lukasm91** [comment]
As far as I remember the idea of consistency checks was to check in general whether we have valid SIR, which is not trivial. This check here is a simple check in the sense that it can be easily implemented, other things that we might want to check:
- Are all field ids properly used
- the protobuf currently allows to create expressions that are not valid because `Expr` is very generic
- Messing up something is also possible with the AST design I think (you can mess up IIR and SIR nodes, which is similarly likely or unlikely as this thing here)

When checking for valid SIR I think it's a valid point to check that all extents / offsets have the required grid type because a pass might do some computations with extents or offsets and output the wrong type (or the pass might be accidentally activated but only be designed for one grid type). As the check is not very hard to be implemented, I would just go for it, but maybe we should first have a task where we figure out what consistency checks we should implement and then we can derive tasks from this.
