### ISSUE TITLE
Separate and move headers in gtclang/gridtools

### ISSUE THREAD

**Issue by Stagno** [MeteoSwiss-APN/dawn#453]
`gtclang/src/gridtools` contains mixed headers. Some belong to gtclang, as they are related to gtclang DSL, like `storage_dsl.hpp`. Others are only needed by generated codes, like `storage_runtime.hpp`. Maybe there are also some which are needed by both contexts (just a doubt, didn't check).
Headers related to generated code should be moved to dawn, as we will need them to run generated code from dawn tests. Also the "shared" headers should be moved to dawn. The others should stay, but maybe a different directory structure should be chosen, as `gridtools/clang` doesn't make much sense.

**Comment by cosunae** [comment]
part of the task is to install the headers
