### ISSUE TITLE
globals optimized away can still be set

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/dawn#457]
In the following code

```
stencil copy_stencil {
    storage in, out;
  
    Do {
  
      vars=1;
      if(vars) {
        vertical_region(k_start, k_end) {
          out = in;
        }
      }
    }
 };
```

`vars=1` is accepted and still the if might be optimized away if the global is set within a --config

**Comment by twicki** [comment]
This problem can be solved in various places:
- In the front end by analysing the `var_access_expr` and comparing if the `name` matches a name of a `global_variables` that has the `is_constexpr` flag set to `true`. If we choose this approach, we prevent **GTClang** from generating invalid SIR but do not have a check in **dawn**.
- In the SIR -> IIR transformation: At this stage we have the information that this is a constexpr field and that we're setting it so we can abort here.

Most likely both are useful but doing it only in the back end should suffice for now.

**Comment by twicki** [comment]
Attached the config, the file and the generated SIR
[test.zip](https://github.com/MeteoSwiss-APN/dawn/files/4030582/test.zip)
