### ISSUE TITLE
Implement an SIR concept for global indexing

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/dawn#471]
in #399 corner and edge handling was proposed for the IIR.

We should work on having an SIR implementation for it

**Comment by cosunae** [comment]
could we make it in a way that  it generates two executables ? one for patches that are touching an edge and other for the rest ? so that all the conditionals or special region computations are simply removed

**Comment by twicki** [comment]
see https://github.com/MeteoSwiss-APN/dawn/pulls
