### ISSUE TITLE
Use location type for structured grids

### ISSUE THREAD

**Issue by jdahm** [MeteoSwiss-APN/dawn#476]
Dawn has a [location type](https://github.com/MeteoSwiss-APN/dawn/blob/7eb7d19e7ce9ee94e5bddfbea2bd0450505ae369/dawn/src/dawn/AST/ASTExpr.h#L55), but it's not used for structured grids.

**Comment by Stagno** [comment]
Since #602 cartesian/structured fields do not have a location type anymore. This was discussed and the conclusion was that this concept doesn't make sense for cartesian grids.
