### ISSUE TITLE
Document ICON pattern 

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/dawn#489]
DoD: collect in a document all the computational patterns studied in ICON dycore, 
highlighting the new ones and provide proposed concepts (if clear)

**Comment by Stagno** [comment]
status: still going through `mo_solve_nonhydro.f90`

**Comment by cosunae** [comment]
https://docs.google.com/document/d/1Zw_lkw364GTBl-ztxvM9EWTCCoi0sB0nH7qCGi7bJXc/edit?usp=sharing

**Comment by cosunae** [comment]
This is the latest summary for public 
https://docs.google.com/document/d/12wCqLuHg09-N12uLpFIMYC2ik9XIFHSwe6veIGBWLVo/edit?usp=sharing
