### ISSUE TITLE
design concept for multi-level neighbour reduce

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/dawn#491]
In order to support the following 9 point stencil, 12 point stencil...

for example encoding the chain of neighbour search c ->v ->c, or c->c->c
![image.png](https://images.zenhubusercontent.com/5db41a74b233b50001b2beae/42c1151e-8efc-4a90-9f4a-4045d6bf64c2)

![image](https://user-images.githubusercontent.com/6085761/68860291-8a8f1180-06e9-11ea-8edd-e9722f0eb123.png)

**Comment by havogt** [comment]
Is it equivalent to 2 reductions executed one after the other?
