### ISSUE TITLE
fields with multiple dimensions on different location types

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/dawn#513]
Define fields with multiple location types:

```
field u(edges, vertex);
```
The idea is to allow for multiple location types in a field, where the first location type is always considered a dense dimension and the rest are sparse dimensions. 
While in a triangular grid the dimensionality is fixed for a given pair (location1, location2), the idea is to specify multiple locations instead of dimension length, since it carries more semantics (and is equally simple)

* make the location type a repeated argument
https://github.com/MeteoSwiss-APN/dawn/blob/e661836aa63ebff0507cbee5607b843c7f745dc2/dawn/src/dawn/SIR/proto/SIR/statements.proto#L47

Then at the code generation, I think we can safely assume triangular grid and specify a fix dimensionality of the extra dimension: 

(cell, edge) ->3
(cell, cell) ->3
(cell,vertex)->3
(edge, edge)->4
(edge, cell) ->2
(edge, vertex) -> 2
(vertex, edge) -> 6
(vertex, cell) -> 6
(vertex, vertex) ->6
https://github.com/ecmwf/atlas/blob/8250c18bca4b3ee9e0c2d66d7137e16f4d4ea989/src/apps/atlas-benchmark.cc#L338

**Comment by Stagno** [comment]
If I'm correct, the only use case we identified that could motivate supporting sparse dimensions is the diamond pattern. But then I realized, by looking at the calculation of `dvt_norm` 
```
dvt_norm(je,jk) = u_vert(ividx(je,jb,4),jk,ivblk(je,jb,4)) * &
                              p_patch%edges%dual_normal_vert(je,jb,4)%v1 + &
                              v_vert(ividx(je,jb,4),jk,ivblk(je,jb,4)) * &
                              p_patch%edges%dual_normal_vert(je,jb,4)%v2 - &
                             (u_vert(ividx(je,jb,3),jk,ivblk(je,jb,3)) * &
                              p_patch%edges%dual_normal_vert(je,jb,3)%v1 + &
                              v_vert(ividx(je,jb,3),jk,ivblk(je,jb,3)) * &
                              p_patch%edges%dual_normal_vert(je,jb,3)%v2)
```
that it requires 2 specific vertices of the diamond. However this is not theoretically compatible with a dynamic dimension (as sparse dimensions imply): what does vertex 3 and 4 of n (with n dynamic) mean? Clearly here we would fix n=4 and set the first 2 weights to 0 (as suggested in the ICON DSL Concepts document https://docs.google.com/document/d/12wCqLuHg09-N12uLpFIMYC2ik9XIFHSwe6veIGBWLVo), but we would break the underlying assumption of a sparse dimension having dynamical size, as we generally assume our grid is unstructured. Similar reasoning for `kh_smag_e` and `z_nabla2_e`.
A sparse dimension makes sense to me only when each sparse element is considered the same, regardless of its relative position.

**Comment by Stagno** [comment]
After discussing with Matthias, we realized that there was some confusion around what we meant by "sparse dimension" as he argues that the size is fixed at compile time, while I assumed it was dynamical. So from now on I will refer to these as "static sparse dimension" vs "dynamic sparse dimension".
What we really want to support is only the static one, as we haven't seen so far use cases for the other. I think the user should specify with the DSL on which kind of grid his/her code is valid (triangular, unstructured, etc.) and this information should be propagated to SIR and IIR. If the grid is unstructured, the user shouldn't be allowed to use static sparse dimensions. In any other case, the static sparse dimenions' sizes would be known for each combination: e->c, c->v, etc.  
Also, knowning the size of the sparse dimension at compile time allows to check that, in a reduction that involves a field defined on such sparse dimension, the weight array has the correct size (same as the dimension's).

**Comment by Stagno** [comment]
Also I think we should limit a field definition to one sparse dimension only. Multiple are unnecessary for our use cases.
This doesn't mean that we can't go through multiple levels of neighbors, as it is a different concept: `field u(edges, edges->cells->vertices)` is an array of 4 for each edge, while `field u(edges, cells, vertices)` is an array of 6 for each edge (2 vertices are shared). The latter, i believe, we wouldn't need.

Also I'd go for the following notation:
```
field u(edges)  // dense
field v(edges->cells)  // sparse
field w(edges->cells->vertices)  // sparse
```
This can be still encoded in SIR/IIR as you suggested, by a repeated `LocationType` argument.

**Comment by cosunae** [comment]
makes perfect sense to me, what you described above, just one remark. 
I think that the assumption of triangular grid (and therefore limit to static sparse dimension) would be applied only at the code generation, where we generate fields with a fixed size and in the syntax that allows to specify weights to solve the diamond, but that is a different task #515 .

In most of dawn (except codegen) we would see only a vector of location types, which do not distinguish between static and dynamic. 

Also do we need sparse dimension that do not have a first dense dimension: ?
`field v(edges->cells)  // sparse
field w(edges->cells->vertices)  // sparse`

**Comment by Stagno** [comment]
I think #515 is about just adding the weights vector, but there is still no way to check the correct size of the vector. We would need to introduce something on DSL, SIR and IIR that specifies which kind of structured grid (triangular, cartesian, ...) the code is intended for, in order to do consistency checks on the weights vector and code generation (when translating the reduction with weights).
Say I write:
```
field in(cells->vertices);
reduce(cells, +, in, [1, -1, 1]);
```
then our code implementing the reduction with weights should iterate through the vertex neighbors of a cell and at the same time iterate through the weights vector. If the number of iterations is different (because, for example, we provided a lat long grid) we have a problem and we generate code that does out of range accesses.
We could infer the dimension sizes from the sizes of the weight vectors but it is hacky and very error prone for the DSL user. Writing instead something like:
```
gridtype triangular;
field in(cells->vertices);
reduce(cells, +, in, [1, -1, 1]);
```
makes it clear from the beginning and also allows checks at the DSL level (which we should also repeat at SIR level).

**Comment by Stagno** [comment]
Answering to the second part of the comment:
The dense dimension is already specified as first element of the "list": 
`**edges**->cells->vertices`.
At the end we only want to define a field on one dense/sparse dimension, plus maybe vertical and extra dimensions.

**Comment by cosunae** [comment]
Ok, now I understand. It was confusing since the semantic of the parameter changes, first argument is either a dense or a sparse depending on whether is a simple location or a chain. 
I would find it it more clear to make it more explicit:

```
field u(edges)  // dense
field v(edges, edges->cells)  // sparse
field w(edges, edges->cells->vertices)  // sparse
```

**Comment by Stagno** [comment]
The notation flavor is a DSL matter, so we probably don't need to care.
What we care about is how we represent it in the SIR/IIR and I would go for the list of `LocationType`s in a `Field` as you were suggesting. A dense dimension would be `{LocationType::Edges}`, a sparse one `{LocationType::Edges, LocationType::Cells}`.

**Comment by Stagno** [comment]
Carlos and I have an implementation of Fields with dense + sparse dimensions almost ready.
There are some problems with `StencilFunctionInstantiation` with nested function calls preventing it to work. A followup issue aims at solving such problems.
