### ISSUE TITLE
Add basic type checking for reductions

### ISSUE THREAD

**Issue by mroethlin** [MeteoSwiss-APN/dawn#516]
Currently, there is no type checking for the location types in conjunction with the reduce over neighbors concept. Code like the following pseudo code:
```
cellField = reduce(edgeField, VertexField)
```
will generate and execute (and possibly/hopefully segfault).

Introduce basic type checking for the reduce over neighbor concept and reject inconsistent code. This can be implemented as an additional Pass in the Optimizer.

DoD: Write tests starting from both consistent and inconsistent IIR and assert that compilation succeeds or fails, respectively

**Comment by mroethlin** [comment]
Maybe this should be blocked by #467 such that the tests could immediately be placed in the correct location?

**Comment by ofuhrer** [comment]
Not sure how to do this. For example, for upstream advection on a Cartesian grid, the upwinded flux would be flux_at_edge = value_at_cell_center_to_right, which seems like a type error.

**Comment by mroethlin** [comment]
fair enough, but what you describe is not a reduction (but a copy). On a side note: copies between different field types probably also need some care (e.g. there are less cells then there are edges, so loop boundaries need to be set accordingly), such that a `copyXtoY` concept might be necessary (which could then be type checked)
