### ISSUE TITLE
Prototype python bindings for atlas

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/dawn#523]

**Comment by lukasm91** [comment]
State January 7:
- I created a temporary atlas4py repository --> we need to figure out where we want to put this repository (clone atlas into gridtools organization and put it there? Standalone repository?). https://github.com/lukasm91/atlas4py
- This is currently only a basic draft. It provides a `_atlas4py` module that is enough to reproduce the atlas diffusion example (https://github.com/MeteoSwiss-APN/dawn/blob/master/dawn/prototype/atlasDiffusionDriver.cpp) in python.
- We are still missing the actual python module that uses `_atlas4py` and provides `atlas4py` and I guess some infrastructure work (I guess this should be a task for GT4Py)
- We should sit together with maybe Christian and see whether we use atlas properly and which features we should expose and use

Conclusion: The C++-part of this task is currently more or less done (but can be extended infinitely). We will need to talk to python experts (to create an actual python module), atlas experts (to expose the right information), and take a strategic decision on where to put these bindings.

**Comment by lukasm91** [comment]
I tried out the bindings in a jupyter notebook that I will put into the repository as well. The idea of the jupyter notebook is to reproduce what the prototype did. To do this, I also created the skeleton code needed to run dawn-code; all this must be considered experimental right now.
