### ISSUE TITLE
issue with new python bindings

### ISSUE THREAD

**Issue by mroethlin** [MeteoSwiss-APN/dawn#557]
On my machine there is an issue with the build script for when generating the python proto files as of commit a67b66afb9182e0b52d2c4c8497af69e166eed79 (Master). The issue is here 

```
  add_custom_target(DawnSIRPythonProto ALL
    COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/python/dawn/
    COMMAND ${CMAKE_COMMAND} -E copy ${sir_proto_python_files} ${CMAKE_BINARY_DIR}/python/dawn
    COMMAND ${CMAKE_COMMAND} -E copy ${sir_proto_python_files} ${CMAKE_SOURCE_DIR}/src/dawn4py/serialization/SIR
    DEPENDS ${sir_proto_python_files}
  )
```

the second `COMMAND` fails, even though `${CMAKE_BINARY_DIR}/python/dawn` exists. Commenting this line out fixes the problem in the sense that the build completes. This goes for both running cmake in the bundle directory as well as using the virtual env as described in the [README](https://github.com/MeteoSwiss-APN/dawn/tree/master/dawn/src/dawn4py/README.md)

**Comment by twicki** [comment]
this is resolved
