### ISSUE TITLE
Support Global Iteration Spaces in the CUDA code-generation

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/dawn#560]
Currently we only support global iteration spaces in the c++-naive back end. This should be extendable to the cuda code generation. 
Pointers to where to change things / where to draw inspiration:
https://github.com/MeteoSwiss-APN/dawn/blob/87969caf9d1c57050cbe3e8aa22788c0ae475f97/dawn/src/dawn/CodeGen/Cuda/MSCodeGen.cpp#L555-L559

https://github.com/MeteoSwiss-APN/dawn/blob/87969caf9d1c57050cbe3e8aa22788c0ae475f97/dawn/src/dawn/CodeGen/CXXNaive/CXXNaiveCodeGen.cpp#L473-L492

An example code for this can be found in 
https://github.com/MeteoSwiss-APN/dawn/blob/master/dawn/examples/python/global_index_stencil.py

**Comment by eddie-c-davis** [comment]
Implemented here:
[https://github.com/eddie-c-davis/dawn/tree/global_index_cuda](url)
PR to come.
