### ISSUE TITLE
corner/edges design for triangular grid regions

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/dawn#579]
Study if the concept that deals with corner/edges is also applicable, and can be used for triangular grid regions like shown here:
https://docs.google.com/document/d/1Zw_lkw364GTBl-ztxvM9EWTCCoi0sB0nH7qCGi7bJXc/edit?usp=sharing

**Comment by mroethlin** [comment]
A document describing how this could be achieved is here:
https://docs.google.com/document/d/1UAX284E-TVIxnRIa1ydHvVppqGOzt3JHUoaJSq04A8E/edit?usp=sharing
