### ISSUE TITLE
Stage location type is not set/updated

### ISSUE THREAD

**Issue by Stagno** [MeteoSwiss-APN/dawn#592]
- [x] Fix in parallel group #797 
- [x] Fix stage merger #831 
- [x] Check if other passes (PassStencilSplitter?, PassIntervalPartitioning?) need fixing
- [ ] Add checks to PassValidation

**Comment by twicki** [comment]
conclusion:

- We use `optional` to implement the [Blackboard pattern](https://en.wikipedia.org/wiki/Blackboard_(design_pattern)). 
- This could also work for stage location type.
- If we opt to go for this route, IIR-completeness can be checked by checking if all of them are set
- Unclear if the stage-splitter does the correct thing @Stagno ?
- Unclear if this is set ever going from SIR to IIR and if our tests didn't catch it @Stagno ?

**Comment by Stagno** [comment]
I looked at the usages of `Stage::setLocationType()`: it's only used by `IIRBuilder`. This means:
- Currently stage splitting does not fix the location type of the stage (the default value = cells is kept). I.e.: we only added the possibility to set a location type to the stage. The logic to set/update such information is yet to be implemented (that's why I created this task).
- Going from SIR to IIR we don't set the location type (again the default is kept). We don't have tests that check the Stage's location type.

Note on usage of `std::optional` to represent information which could be "not yet computed": even if the name optional suggests another thing, this class can be used to serve exactly the purpose of representing an information which is not there yet. We could still hide it behind an API.

**Comment by Stagno** [comment]
DoD:
- make `Stage::type_` an `optional` (or whatever way to represent an information which could be not yet computed).
- fix stage splitter to correctly set the location type of the stages
- fix any code touching a Stage to keep this information up to date (not sure if there's any)
- write tests to check whether statements inside a Stage match the Stage's location type specification
