### ISSUE TITLE
Fix dockerfile tests

### ISSUE THREAD

**Issue by jdahm** [MeteoSwiss-APN/dawn#610]
Every commit currently has a red x next to it because a test called "ci/dockercloud (/gtclang/Dockerfile)" is failing. Let's replace that with Travis testing or disable altogether.

**Comment by jdahm** [comment]
@cosunae I don't have access to the gtclang user at https://hub.docker.com/u/gtclang. Do you have access? Could someone go in and disable/remove those? Once things settle in the repository I'll have a set of dockerfiles that build up different components of the toolchain, and we can use one of those to deploy there.

**Comment by twicki** [comment]
duplicate of https://github.com/MeteoSwiss-APN/dawn/issues/623
