### ISSUE TITLE
Refactor the ASTVisitor

### ISSUE THREAD

**Issue by mroethlin** [MeteoSwiss-APN/dawn#617]
Currently, there are the following interfaces offered for writing an AST Visitor:

`ASTVisitor::visit(const std::shared_ptr<T>& stmt);`
And
`ASTVisitorNonConst::visit(std::shared_ptr<T>& stmt);`

Presumably, the intention was to offer both an interface for queries on the AST, leaving the Stmt's and Expr's constant, and one for transforming the AST. The above interface does not provide that, the `const`in the latter interface refers to the `shared_ptr`, not its content. Thus, refactor the AST Visitors to actually provide the semantics described, e.g. using:

`ASTVisitor::visit(const T& stmt);`
And
`ASTVisitorNonConst::visit(std::shared_ptr<T>& stmt);`

There is yet another Issue with the Forwarding Visitor noticed during the generalization of the weights: The forwarding visitor does not correctly forward into the stencil body of a function. Which, however, is implied by the name. See `WeightChecker` or `PassTemporaryFirstAccess` to see how this can be achieved.

**Comment by havogt** [comment]
Probably `ASTVisitorNonConst::visit(T& stmt);` as well. I guess the visitor newer takes ownership?

**Comment by PanicSheep** [comment]
How about renaming them _NodeVisitor_ and _NodeTransformer_?
The name "transformer" implies that it changes the nodes.
The "visitor" might need comments to state that it doesn't change the nodes.
(I took the idea from python's _ast.NodeVisitor_ and _ast.NodeTransformer_)
