### ISSUE TITLE
Design: Teamwide decision on SIR concepts and the parallel model (IIR)

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/dawn#647]
In #559 we discussed some options for improving the parallel model concepts of SIR. 
Still some ideas were not understood in detail. 
DoD. finalize the discussion of all alternatives for SIR (started in #559), and write a proposal documenting the changes proposed for SIR. 
Also discuss the parallel model of IIR and propose the desire modifications to current IIR.

**Comment by twicki** [comment]
After discussions we came to the following conclusion:
1) @havogt 's initial proposal on how to interpret **current** SIR is the same as @Stagno 's
2) There can be and independent discussion on if we enrich SIR with @Stagno 's proposal of adding a new enum parallel to the loop order (with its specific parallel model interpretation for the new concept)
3) There can be an independent discussion on if we want to make the syntax of the SIR more rigid to only allow writes in declarations of either local variables or temporaries
4) We're still missing the proposal from @havogt 
The existing material is composed here:

**Comment by twicki** [comment]
[parallelModel.txt](https://github.com/MeteoSwiss-APN/dawn/files/4133991/parallelModel.txt)

**Comment by havogt** [comment]
> @havogt 's initial proposal on how to interpret current SIR is the same as @Stagno 's

In @Stagno 's proposal it is not clear to me if you deduce the loop order for a solver or if it is defined by the order kstart, kend.

**Comment by twicki** [comment]
Every loop has a defined order

**Comment by havogt** [comment]
So basically we have 2 proposals
- Your, Giacomo, my proposal (with an optional parallel)
- Lukas' idea
