### ISSUE TITLE
Stencil function instantiation map not serialized in IIRSerializer

### ISSUE THREAD

**Issue by eddie-c-davis** [MeteoSwiss-APN/dawn#672]
The ```StencilFunCallExpr``` to ```StencilFunctionInstantiation``` map, ```ExprToStencilFunctionInstantionMap_``` in ```StencilMetaInformation``` is not serialized or deserialized in the ```IIRSerializer``` class. This means that serializing the IIR for gtclang integration tests such as ```RaceCondition03``` throws an ""Invalid stencil function" error because the mapping is not found in the ```StencilMetaInformation``` object.

**Comment by twicki** [comment]
This is since the assumption that we inline before serializing was taken. We can think about serializing functions as well

**Comment by eddie-c-davis** [comment]
This issue has been resolved in the [split_tests](https://github.com/eddie-c-davis/dawn/tree/split_tests) branch by beginning with SIR and running the inlining pass
