### ISSUE TITLE
Refactor CodeGen tests

### ISSUE THREAD

**Issue by eddie-c-davis** [MeteoSwiss-APN/dawn#700]
Refactor GTClang CodeGen integration tests as Dawn unit tests by beginning with IIR, generating code, and comparing it to some reference. This could be either source code, e.g., C++ or CUDA; or an intermediate representation, e.g., LLVM-IR or PTX.

**Comment by eddie-c-davis** [comment]
Per team discussion, the scope of each unit test should be:
* Deserialize IIR with parallelization pass applied
* Generate simple data set with C++ for loops in each
* Perform code generation using naive C++ backend (for now)
* Compile and execute the generated code
* Assert that the data are matching

**Comment by twicki** [comment]
subtasks are opened in favour of that
