### ISSUE TITLE
rework dawn integration tests: serializer

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/dawn#765]
These seem to be unittests for serialization.

For deserialization: Consider starting at files and assert properties.

For serialization generate simple in memory and compare against reference (as is right now).

Note there are unittests in dawn/IIR/IIRSerializer which combine serialization and deserailization. 

Merging what we have there and here should lead to comprehensive tests

**Comment by mroethlin** [comment]
"For deserialization: Consider starting at files and assert properties."
Currently, we start at a file and compare for equality against an in memory constructed reference. I don't really see a clear advantage by replacing this equality check with isolated checks for certain properties. Wouldn't we then simply just run a subset of the checks we are running now?

**Comment by twicki** [comment]
sorry, apparently this was test-audit overflow.

This folder here deserializes files and compares iirs. That is what we should do.

Serialization is not really covered here. The only time we check that is in unit-test/IIR/TestIIRSerializer which does serialization and deserialization
