### ISSUE TITLE
rework dawn unit test: dawn/Optimizer/TestsFromSIR

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/dawn#778]
These are the prime example of integration tests. Move them there and assert on properties of the iir after some passes (default group) are ran

**Comment by mroethlin** [comment]
as far as I can see this is what's currently done, except all passes are ran instead of the default group only. So this boils down to moving the tests and ensure that only the default group is ran?

**Comment by twicki** [comment]
I would say so
