### ISSUE TITLE
rework dawn unit test: dawn/Validator

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/dawn#782]
does not have a main, reflect what others are doing

**Comment by mroethlin** [comment]
is it supposed to have a main? if so, why? which parts of other tests should be reflected?

**Comment by twicki** [comment]
There are currently two approaches in our repo:
- Have a TestMain (https://github.com/MeteoSwiss-APN/dawn/blob/master/dawn/test/unit-test/dawn/Optimizer/Passes/TestMain.cpp) and link to that
- link to `gtest_main` (https://github.com/MeteoSwiss-APN/dawn/blob/2d450d1f04a0f6584e1ab4cde0a5af27f47c3db3/dawn/test/unit-test/dawn/Validator/CMakeLists.txt#L22)

On further thought I don't think we need consistency throughout  since there are tests that require arguments and we would need a main for it whereas this would create overhead for the other tests.

If you agree @mroethlin, you can just close this one.

**Comment by mroethlin** [comment]
agreed
