### ISSUE TITLE
Document changes to neighbor chains and ordering of neighbors

### ISSUE THREAD

**Issue by Stagno** [MeteoSwiss-APN/dawn#855]
Follow up task of #843

DoD: update wiki to reflect changes described here https://docs.google.com/document/d/1jA4lojFLrJEssYTzUT-o_0auobLqU3fnQB11YjFkaiE/edit

**Comment by mroethlin** [comment]
the [wiki article](https://github.com/MeteoSwiss-APN/dawn/wiki/Unstructured-sparse-dimension) was adapted
