### ISSUE TITLE
Global variables in SIR should not always need value

### ISSUE THREAD

**Issue by jdahm** [MeteoSwiss-APN/dawn#934]
We cannot deserialize globals without a value set. In fact, in this case there is no information about the data type written into the SIR. This situation needs fixing so there is a clear bijection between the in-memory and serialization.

Relevant code references:
- Globals in the SIR protobuf: https://github.com/MeteoSwiss-APN/dawn/blob/master/dawn/src/dawn/SIR/proto/SIR/SIR.proto#L88
- Serialization happens here: https://github.com/MeteoSwiss-APN/dawn/blob/master/dawn/src/dawn/Serialization/SIRSerializer.cpp#L190
- Deserialization happens here: https://github.com/MeteoSwiss-APN/dawn/blob/master/dawn/src/dawn/Serialization/SIRSerializer.cpp#L734

 #931 fixes the immediate bug by using default initialization, but this is only a temporary fix. Long-term we need to allow unset globals, if globals are necessary...

**Comment by Stagno** [comment]
I think it's worth to first re-discuss globals to see if we really need them or if there is a better way to have the functionality of a constant (within the stencil) value which is domain-global, then see how to fix this, if it will be needed.

**Comment by jdahm** [comment]
We have a work-around implemented in https://github.com/MeteoSwiss-APN/dawn/pull/931.
