### ISSUE TITLE
GCC 10.1 fails due to globals in `CXXUtil.h`

### ISSUE THREAD

**Issue by BenWeber42** [MeteoSwiss-APN/dawn#973]
`CXXUtil.h` defines the following globals: https://github.com/MeteoSwiss-APN/dawn/blob/727835e027b8270d667452b857fa4e0af57b2c2e/dawn/src/dawn/CodeGen/CXXUtil.h#L672
```C++
auto c_gt = []() { return Twine("gridtools::"); };
auto c_dgt = []() { return Twine("gridtools::dawn::"); };
auto c_gt_enum = []() { return Twine("gridtools::enumtype::"); };
auto c_gt_intent = []() { return Twine("gridtools::intent::"); };
```

GCC 10.1 fails for those, since this header is included multiple times and thus the global variables `c_gt`, etc will be defined multiple times. This leads to errors during the linking stage.

One way we could resolve this is by using only function declarations (without implementation) in the header like so:
```C++
Twine c_gt();
...
```

And then implement those functions in an appropriate `.cpp` file. However, `CXXUtil.h` is currently _header only_, so we'd probably want to introduce a corresponding `.cpp` file and add it to the cmake files.

I think there might also be ways to make the linker happy while keeping the implementations in the header. Maybe the `inline` or `constexpr` keywords could help. I haven't been able to investigate this a lot.

**Comment by Stagno** [comment]
I would go for `constexpr`. Adding a `.cpp` and cmake for just 4 lines of "implementation" doesn't make much sense.

**Comment by havogt** [comment]
`constexpr inline`!

But I guess the cleanest solution would be 
`constexpr inline Twine c_gt = "gridtools::";` etc.
No need for a lambda as far as I can see.

**Comment by BenWeber42** [comment]
What's the minimum C++ version that dawn supports? Inline variables are only available since C++17: https://en.cppreference.com/w/cpp/language/inline

Also `constexpr` implies `inline` in some cases for variables (since C++17):

> The inline specifier, when used in a decl-specifier-seq of a variable with static storage duration (static class member or namespace-scope variable), declares the variable to be an inline variable.
> A static member variable (but not a namespace-scope variable) declared constexpr is **implicitly an inline** variable.

I think we should try with `constexpr` the way hannes suggested and see if it works? If necessary we can still add `inline`.

**Comment by havogt** [comment]
We are C++17.

**Comment by jdahm** [comment]
I read that `constexpr` support for strings and vectors only getting added in C++20. Is that right @havogt? Maybe defining these in an inline function, or in the source would be better.

**Comment by BenWeber42** [comment]
That's correct: https://stackoverflow.com/a/43335753/12958632
