### ISSUE TITLE
Invalid SourceLocation comparison

### ISSUE THREAD

**Issue by stefanmoosbrugger** [MeteoSwiss-APN/dawn#99]
Is this a bug or intended? 
`https://github.com/MeteoSwiss-APN/dawn/blob/master/src/dawn/Support/SourceLocation.cpp#L25`

```c++
extern bool operator==(const SourceLocation& a, const SourceLocation& b) {
  return a.Line == b.Line && b.Column == b.Column;
}
```
I guess it should be `.. && a.Column == b.Column`.

**Comment by cosunae** [comment]
@stefanmoosbrugger did u fix this one? can we close it?

**Comment by stefanmoosbrugger** [comment]
@cosunae can be closed.. got fixed with https://github.com/MeteoSwiss-APN/dawn/pull/100
